version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app.db:/NightWing/app.db
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app
      FLASK_ENV: development